### ISSUE TITLE
Algorithm description

### ISSUE THREAD

**Issue by dselivanov** [Microsoft/ISLE#4]
Is there any paper which describes algorithm? I found [slides](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/07/Provable_Alogorithms_for_ML-AI_Problems_Kannan.pdf), but they lack details. Especially first step where thresholds are calculated.

**Comment by dselivanov** [comment]
@harsha-simhadri any tips?

**Comment by harsha-simhadri** [comment]
Partly based on https://arxiv.org/abs/1410.6991 and some other unpublished work

**Comment by dselivanov** [comment]
Thanks!
